<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <CopyLocalLockFileAssemblies>true</CopyLocalLockFileAssemblies>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <ReleaseVersion>1.3.1-pre</ReleaseVersion>
    <EnableDynamicLoading>true</EnableDynamicLoading>
    <Configurations>Debug;Release;Migration</Configurations>
    <IsPackable>false</IsPackable>
  </PropertyGroup>

  <PropertyGroup>
    <OutputPath>..\..\src\LeadCMS\bin\$(Configuration)\$(TargetFramework)\plugins\$(AssemblyName)</OutputPath>
    <AppendTargetFrameworkToOutputPath>false</AppendTargetFrameworkToOutputPath>
  </PropertyGroup>

  <ItemGroup>
    <Content Include="pluginsettings.json">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
  </ItemGroup>

  <ItemGroup Condition="'$(Configuration)'!='Migration'">
    <ProjectReference Include="..\..\src\LeadCMS\LeadCMS.csproj">
      <Private>false</Private>
      <ExcludeAssets>runtime</ExcludeAssets>
    </ProjectReference>
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.TeamFoundationServer.Client" Version="19.225.1" />
    <PackageReference Include="Microsoft.VisualStudio.Services.Release.Client" Version="19.225.1" />
  </ItemGroup>

  <ItemGroup>
    <Folder Include="Configuration\" />
    <Folder Include="Services\" />
  </ItemGroup>

  <!--This ItemGroup is required to support migration generating with the "dotnet ef migrations add" command-->
  <ItemGroup Condition="'$(Configuration)'=='Migration'">
    <ProjectReference Include="..\..\src\LeadCMS\LeadCMS.csproj" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Design" Version="8.0.11">
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
      <PrivateAssets>all</PrivateAssets>
    </PackageReference>
  </ItemGroup>
</Project>
