name: PR & Develop - Build & Test

on:
  push:
    branches: [ "main", "develop" ]
  pull_request:
    branches: [ "main", "develop" ]

env:
  BUILD_CONFIG: Release
  DOTNET_VERSION: 8.0.x

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6

      - name: Setup .NET
        uses: actions/setup-dotnet@v5
        with:
          dotnet-version: ${{ env.DOTNET_VERSION }}

      - name: Restore dependencies
        run: dotnet restore

      - name: Build
        run: dotnet build --configuration ${{ env.BUILD_CONFIG }} -p:Version=1.0.0
          --no-restore

      - name: Upload build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: build-output
          path: tests/LeadCMS.Tests/bin/${{ env.BUILD_CONFIG }}/
          retention-days: 1

  test:
    name: Matrix Tests
    needs: build
    permissions:
      checks: write
      contents: read
    uses: ./.github/workflows/reusable-matrix-tests.yml
    with:
      build-artifact-name: build-output
