name: Test Reporter
on:
  workflow_run:
    workflows: ['PR & Develop - Build & Test', 'Release - Build, Test & Publish', 'Manual - Build, Test & Publish (Develop)']
    types:
      - completed
jobs:
  report:
    runs-on: ubuntu-latest
    steps:
      - uses: dorny/test-reporter@v1.9.1
        with:
          name: TRX Tests
          artifact: test-results                                                          # artifact name
          fail-on-error: false                                                            # Supress error on failed tests
          path: '*.trx'                                                                   # Path to test results (inside artifact .zip)
          reporter: dotnet-trx                                                            #Format of test results
